pages = [{"l":"index.html","n":"NegativeGreyChangePhoto","t":"NegativeGreyChangePhoto","d":"","k":"static"},
{"l":"_empty_.html","n":"<empty>","t":"package <empty>","d":"<empty>","k":"package"},
{"l":"_empty_/HandCraftedBMPNegativeMaker.html","n":"HandCraftedBMPNegativeMaker","t":"class HandCraftedBMPNegativeMaker","d":"<empty>/HandCraftedBMPNegativeMaker","k":"class"},
{"l":"_empty_/HandCraftedBMPNegativeMaker.html","n":"byteToUnsignedInt","t":"def byteToUnsignedInt(byte: Byte): Int","d":"<empty>/HandCraftedBMPNegativeMaker","k":"def"},
{"l":"_empty_/HandCraftedBMPNegativeMaker.html","n":"getInputStream","t":"def getInputStream(fileName: String): Array[Byte]","d":"<empty>/HandCraftedBMPNegativeMaker","k":"def"},
{"l":"_empty_/HandCraftedBMPNegativeMaker.html","n":"produceNegative","t":"def produceNegative(fileName: String, processType: String): Boolean","d":"<empty>/HandCraftedBMPNegativeMaker","k":"def"},
{"l":"_empty_/HandCraftedBMPNegativeMaker.html","n":"verifyBMPfile","t":"def verifyBMPfile(inputStream: DataInputStream): Boolean","d":"<empty>/HandCraftedBMPNegativeMaker","k":"def"},
{"l":"_empty_/HandCraftedBMPNegativeMaker.html","n":"write","t":"def write(fileName: String, byteArray: Array[Byte]): Unit","d":"<empty>/HandCraftedBMPNegativeMaker","k":"def"},
{"l":"_empty_/InputHandler.html","n":"InputHandler","t":"class InputHandler","d":"<empty>/InputHandler","k":"class"},
{"l":"_empty_/InputHandler.html","n":"getUserInput","t":"def getUserInput: String","d":"<empty>/InputHandler","k":"def"},
{"l":"_empty_/InputHandler.html","n":"helpCommand","t":"def helpCommand: Unit","d":"<empty>/InputHandler","k":"def"},
{"l":"_empty_/InputHandler.html","n":"introduction","t":"def introduction: Unit","d":"<empty>/InputHandler","k":"def"},
{"l":"_empty_/InputHandler.html","n":"isPathValid","t":"def isPathValid(path: String): Boolean","d":"<empty>/InputHandler","k":"def"},
{"l":"_empty_/InputHandler.html","n":"userInputLoop","t":"def userInputLoop(): (String, String)","d":"<empty>/InputHandler","k":"def"},
{"l":"_empty_/Main$.html","n":"Main","t":"object Main extends App","d":"<empty>/Main$","k":"object"},
{"l":"_empty_/Main$.html","n":"gameLoop","t":"def gameLoop(inputHandler: InputHandler, handCrafted: HandCraftedBMPNegativeMaker, negativeMaker: NegativeMakerUsesImageProcessingLibrary, toContinue: Option[Boolean]): Option[Boolean]","d":"<empty>/Main$","k":"def"},
{"l":"_empty_/Main$.html","n":"inputHandler","t":"val inputHandler: InputHandler","d":"<empty>/Main$","k":"val"},
{"l":"_empty_/Main$$BitCountException.html","n":"BitCountException","t":"class BitCountException(s: String) extends Exception","d":"<empty>/Main$$BitCountException","k":"class"},
{"l":"_empty_/Main$$CompressionException.html","n":"CompressionException","t":"class CompressionException(s: String) extends Exception","d":"<empty>/Main$$CompressionException","k":"class"},
{"l":"_empty_/Main$$HeaderSizeNoteFiftyFourException.html","n":"HeaderSizeNoteFiftyFourException","t":"class HeaderSizeNoteFiftyFourException(s: String) extends Exception","d":"<empty>/Main$$HeaderSizeNoteFiftyFourException","k":"class"},
{"l":"_empty_/Main$$NotBMPFileException.html","n":"NotBMPFileException","t":"class NotBMPFileException(s: String) extends Exception","d":"<empty>/Main$$NotBMPFileException","k":"class"},
{"l":"_empty_/NegativeMakerUsesImageProcessingLibrary.html","n":"NegativeMakerUsesImageProcessingLibrary","t":"class NegativeMakerUsesImageProcessingLibrary","d":"<empty>/NegativeMakerUsesImageProcessingLibrary","k":"class"},
{"l":"_empty_/NegativeMakerUsesImageProcessingLibrary.html","n":"askUserIfTheyWouldLikeToSeePhoto","t":"def askUserIfTheyWouldLikeToSeePhoto: String","d":"<empty>/NegativeMakerUsesImageProcessingLibrary","k":"def"},
{"l":"_empty_/NegativeMakerUsesImageProcessingLibrary.html","n":"getGreyedRGB","t":"def getGreyedRGB(rgbColor: Int): Int","d":"<empty>/NegativeMakerUsesImageProcessingLibrary","k":"def"},
{"l":"_empty_/NegativeMakerUsesImageProcessingLibrary.html","n":"getNegativeRGB","t":"def getNegativeRGB(rgbColor: Int): Int","d":"<empty>/NegativeMakerUsesImageProcessingLibrary","k":"def"},
{"l":"_empty_/NegativeMakerUsesImageProcessingLibrary.html","n":"getPhotoFromFile","t":"def getPhotoFromFile(fileName: String): Option[BufferedImage]","d":"<empty>/NegativeMakerUsesImageProcessingLibrary","k":"def"},
{"l":"_empty_/NegativeMakerUsesImageProcessingLibrary.html","n":"mapOFRGBfucntions","t":"val mapOFRGBfucntions: Map[String, Int => Int]","d":"<empty>/NegativeMakerUsesImageProcessingLibrary","k":"val"},
{"l":"_empty_/NegativeMakerUsesImageProcessingLibrary.html","n":"producePhoto","t":"def producePhoto(fileName: String, proccessType: String): Option[BufferedImage]","d":"<empty>/NegativeMakerUsesImageProcessingLibrary","k":"def"},
{"l":"_empty_/NegativeMakerUsesImageProcessingLibrary.html","n":"saveImage","t":"def saveImage(fileName: String, bufferedImage: BufferedImage): Boolean","d":"<empty>/NegativeMakerUsesImageProcessingLibrary","k":"def"},
{"l":"_empty_/NegativeMakerUsesImageProcessingLibrary.html","n":"transformRGBPixels","t":"def transformRGBPixels(image: BufferedImage, proccessType: String): BufferedImage","d":"<empty>/NegativeMakerUsesImageProcessingLibrary","k":"def"},
{"l":"docs/index.html","n":"NegativeGreyChangePhoto","t":"NegativeGreyChangePhoto","d":"","k":"static"}];